[firebase]
type = "service_account"
project_id = "modular-installation"
private_key_id = "0cdf3d9ffc0744c53598d9e5b41bc273f3723ce9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/zE4a0z8+nLM0
Eg+J7PwxcWSCuC7IGZ39gMl8UYbEA2pzdzL+F6bA0xLjJPfytDxyQ9I51NA4Jxze
IznDS0TsRqyy27ubzXwcz0h5icH26WJbmbypefzMry2nvg+lI6RhcPSia1KKZFcg
757mNF1tQfVjRz8OK0Ujot+osTZDchniUwVHIxZm/OxVlZANEVrcump6lBZHU5yp
70RnfNPJrVmqwC5kZu4t7m3ongNxKW5aLPa0TfgxwOlIK3wx8PqopQQrxQQxYDBO
4K9x9eQJhHEjoMFOeLosLRl5J45ndD4kx78gtlY1TPi1K+etNpxqV9g3arDMw1t7
OJXqoGtrAgMBAAECggEABKMbZlGiL1DZklI3dvW4WTetHu32D5dy9uyUsoFEGVwd
yEHjBTqsKPBRfhVoO0F5TqfuHsDS8fCcJZDDdkHNHktNJJvkas1qiUXHskyO2Hnn
C2Dpq01MO+SmXW5ecXcto7934q9mlPr9EkpI1LcCZUBZfvd7gkuwhb6L2sfCEJpY
Yw3KySXS+ihDP9gXHRHp6mzh+Y5hgA81b1YXLxKzr3rQBWX6aA5EbMCwxp05PfPW
HS+hwnbyCMQ0EGvgYMxVqTlFxQ727u6cQSzqunZz7d+as6egNY7nOIeZTmFo0QTx
geq1vPR5f7NOEOcGb3he0zbRCxc9bhIfw23JkJfb5QKBgQDrHVmeEVNRsJJpv1MC
1UZBgFhrfUEvJw9tPveJigK8Y0u8LWCvnp6m3D5ykrJGpzv02hwmGYFyvtiGDmGL
VmI1VqT9j9Z8dmeAJYDufD5IwHYvgzel3RpGHYF5rjZexnccO+HWCBwfUKkpCZ0F
9lDFabcT/hN2FwNyMeNUJ7SDNwKBgQDQ1ejeX80AafT8jShN28cP73CNlKcmY3GW
ASNuGGLIxOWx0BgyGrzPg+piCrZdCHDQ+/JJrqNnM7KIckP0dvLyoUIwE+/S9KSk
4vwVZacQSV+XnkHebBmU3aodp8RR5GZ39z4E8H/3sV/pKffYLs9/BD2GHf2OrHNv
3JdrOOBbbQKBgQCtCyYJY8EKD8ZDFHDZVfVmgjsRqdePB9Wf10dDMJOA6ig0sMVH
nJwyPUms8/FIdQ940AsFs6IFvRcJ243JiuOvVD0M7o+zfUYCGBhD7qe8zgJuR8pu
RkRvNIo175XOvY2u9xfpeoCQP8KxFIVAfSDHm14G1eqm8Js1sigZqTt/kwKBgAPC
ljrKxsonHj4d3IfqWR80VHZ4IrpSOA1XX+fvkHfE883LzWO5j4S8/09cmgP6zu00
XBxvhImrKJ/ETuzr51vvA14SPdMyjHRbkeZgui1U5N+5/b2ffKZth06ZYrOGxUGL
thYormUrUGrGUqwVy66hyOnNSG91M27kLeXEVGXRAoGAORGIqwZYlVreZGRpUfmU
nhKP0LcTs4HK8i9zSPCX1rcUxIGslbAgjefrRrdLUU/ledqrjCXItRrS0dhmvcmU
jnhQ4h5xwp8jSBxx0gJUaPQ832tOYleAeJyj1t1I0azJQ8CFxMPD4lN96G/JnBo0
MABsGXAxPUsOpIihe7Df3sU=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@modular-installation.iam.gserviceaccount.com"
client_id = "116965076574252675315"